name: mock_exceptions
description: Provides a mechanism to throw exceptions on certain calls. This is useful when working with a Fake and we still want to occasionally make it throw exceptions.
version: 0.8.2
repository: https://github.com/atn832/mock_exceptions
homepage: https://www.wafrat.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  matcher: ^0.12.12

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
